spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/gestor-financas
    password: 123456
    username: postgres

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true